apiVersion: v1
kind: Namespace
metadata:
  name: kube-ipam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ipam
rules:
  - apiGroups: [""]
    resources: ["services", "services/status"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ipam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ipam
subjects:
  - kind: ServiceAccount
    name: kube-ipam
    namespace: kube-ipam
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ipam
  namespace: kube-ipam
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-ipam
  namespace: kube-ipam
  labels:
    app: kube-ipam
spec:
  serviceAccountName: kube-ipam
  containers:
    - name: kube-ipam
      image: ghcr.io/blakelead/kube-ipam:latest
      args:
        - --cidr=192.168.10.0/24
